/**
 * Writes src/generated/sitemap-xml.ts at build time so /sitemap.xml is served
 * by a Next.js route handler with explicit XML headers (more reliable for GSC
 * than public/ static files on Vercel).
 *
 * Run automatically via npm prebuild / predev.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputDir = join(__dirname, "..", "src", "generated");
const outputPath = join(outputDir, "sitemap-xml.ts");

const staticPaths = [
  "",
  "/services",
  "/pricing",
  "/about",
  "/contact",
  "/industries",
  "/showcase",
  "/what-is-seo",
  "/what-is-domain-hosting",
  "/faq",
];

const industrySlugs = ["dentists", "plumbers", "salons"];

function resolveSiteUrl(raw) {
  if (!raw?.trim()) return null;
  try {
    const value = raw.trim();
    const withProtocol = /^https?:\/\//i.test(value) ? value : `https://${value}`;
    return new URL(withProtocol).origin;
  } catch {
    return null;
  }
}

function getSiteUrl() {
  return (
    resolveSiteUrl(process.env.NEXT_PUBLIC_SITE_URL) ??
    (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null) ??
    "http://localhost:3000"
  );
}

function absoluteUrl(base, path) {
  if (!path || path === "/") return base;
  return `${base}${path.startsWith("/") ? path : `/${path}`}`;
}

function escapeXml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

const base = getSiteUrl();
const lastmod = new Date().toISOString().slice(0, 10);

const urls = [
  ...staticPaths.map((path) => ({
    loc: absoluteUrl(base, path),
    priority: path === "" ? "1.0" : "0.8",
  })),
  ...industrySlugs.map((slug) => ({
    loc: absoluteUrl(base, `/industries/${slug}`),
    priority: "0.9",
  })),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    ({ loc, priority }) => `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`,
  )
  .join("\n")}
</urlset>
`;

const ts = `// Auto-generated by scripts/generate-sitemap.mjs — do not edit.
const sitemapXml = ${JSON.stringify(xml)};
export default sitemapXml;
`;

await mkdir(outputDir, { recursive: true });
await writeFile(outputPath, ts, "utf8");
console.log(`Wrote ${outputPath} (${urls.length} URLs, base: ${base})`);
